Write a class that generates fake data.

* Write the code under the py docs ( do NOT remove py docs )
* Before comitting do a Restart & Run All

In [5]:
import pandas as pd
import random

# !pip install Faker

from faker import Faker
class FakeDataGenerator:
    
    def __init__(self, df = None, rows=5):
        """
        This class generates fake data
        
        If data frame is passed in it will add the fake data to it. 
        Otherwise, it will create a new data frame
        
        Parameters:
        -----------
        df: 
          DataFrame default is None
          
        rows:
          If df None, this parameter will be used to create a data frame with `row` lenght
        """
        # code goes under this line. 
        # I will deduct points if any code is written above the comments!
        

        self.fake = Faker()
        
        if df is not None:
            self.df = df
            self.rows = len(df)
        else:
            self.df = pd.DataFrame()
            self.rows = rows
        
        
    def add_random_number(self, column_name, small_value, high_value): # optional: add probabilities 
        """
        adds fake numbers to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        
        self.df[column_name] = [random.randint(small_value,high_value) for i in range(self.rows)]
        
        return self.df      
    
        
    def add_name(self, column_name):
        """
        adds fake name to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        
        self.df[column_name] = [self.fake.first_name() for i in range(self.rows)]
        
        return self.df
    
    
    def add_last_name(self, column_name):
        """
        adds fake last name to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        
        self.df[column_name] = [self.fake.last_name() for i in range(self.rows)]
        
        return self.df
    
    
    def add_email(self, column_name):
        """
        adds fake email to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        
        return self.df
    
    
    def add_phone_number(self, column_name):
        """
        adds fake name to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        
        self.df[column_name] = [self.fake.email() for i in range(self.rows)]
        
        return self.df
    
    
    def add_address(self, column_name):
        """
        adds fake name to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        
        self.df[column_name] = [self.fake.phone_number() for i in range(self.rows)]
        
        return self.df

In [6]:
import pandas as pd

# Case 1 - existing data frame 
df = pd.DataFrame()
df['product_id'] = [i + 123 for i in range(25)]
df.head()

   product_id
0         123
1         124
2         125
3         126
4         127

In [7]:
fakeGen = FakeDataGenerator(df) # I'm creating instance using existing df
fakeGen.add_address('shipping_address')
fakeGen.add_address('billing_address')
fakeGen.add_phone_number('customer_phone')

,product_id,shipping_address,billing_address,customer_phone
0,123,406-993-7451,520.452.5823,yhendricks@tucker-martinez.com
1,124,001-694-540-5439x1646,3586945106,erika77@hotmail.com
2,125,392.221.8972,001-638-923-3110,smyers@perez.com
3,126,001-405-504-2469,+1-691-276-7049,fwagner@garcia-yu.com
4,127,+1-616-872-4369x477,+1-409-568-2604,gerickson@yahoo.com
5,128,(466)750-0165x459,630-741-7157x038,dtyler@glass.com
6,129,(744)874-9425x737,(429)914-1759x1491,lrodriguez@gmail.com
7,130,822-488-7329,169-101-2584x1816,sawyerrhonda@reynolds.net
8,131,6556726667,+1-962-333-7820x782,bsmith@yahoo.com
9,132,+1-250-732-8640x80178,+1-247-106-0486x50641,monicasmith@romero.org
10,133,001-963-082-9614,(020)479-7993x0963,jenniferwebb@barrett.com
11,134,+1-799-687-1781x0439,941-546-1460x1077,klinetara@smith.com
12,135,+1-862-425-3074x62116,+1-480-808-1818x8772,danielrodriguez@melendez.com
13,136,(885)311-4596,(228)492-9365x790,jbowen@garrett.com
14,137,+1-880-274-8563x776,(108)336-2922x9053,wellsdavid@yahoo.com
15,138,(071)510-4263x008,001-922-931-8939,rthomas@torres.net
16,139,(992)328-8877x0148,936.993.4627x9675,jason07@yahoo.com
17,140,189-384-4755x298,+1-759-356-9759,sandrawest@tucker-cox.org
18,141,+1-057-205-6336,+1-821-916-3258x6464,qtorres@yahoo.com
19,142,073.322.9804,(899)829-3487x58105,julieferguson@villegas-molina.com
20,143,001-686-0931x83639,(267)495-4135,thompsonrobin@martinez-ross.net
21,144,001-890-277-8595,(391)303-9381x2792,austinbush@yahoo.com
22,145,(963)776-2957,001-199-753-7157x8083,amandamcdaniel@yahoo.com
23,146,912-440-1319x342,(873)808-3070,butleramanda@yahoo.com
24,147,(177)255-5729,(057)880-6200x48075,acarr@wilson.info

In [8]:
# Case 2 - no dataframe

fakeGen = FakeDataGenerator() # no df
fakeGen.add_address('shipping_address')
fakeGen.add_address('billing_address')
fakeGen.add_phone_number('customer_phone')
fakeGen.add_random_number('sale_count', 10, 100)

,shipping_address,billing_address,customer_phone,sale_count
0,+1-828-435-7797x56438,283.851.6942,alex95@yahoo.com,87
1,001-246-464-1202x26209,(779)771-1095x6354,glamb@gmail.com,71
2,+1-408-474-1440x7504,(972)933-6936x5450,briannafoster@garner.com,16
3,880-400-5162x691,(814)055-6876x6261,hoopernicole@hotmail.com,34
4,001-107-095-6985x7937,462.953.2249x9508,samanthacole@yahoo.com,52